services:
  - type: web
    name: warframe-inventory
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    renderSubdomainPolicy: enabled
    autoDeployTrigger: commit
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: WARFRAME_TRACKER_DATABASE_PROVIDER
        value: MySql
      - key: WARFRAME_TRACKER_DB_HOST
        sync: false
      - key: WARFRAME_TRACKER_DB_PORT
        value: "3306"
      - key: WARFRAME_TRACKER_DB_USER
        sync: false
      - key: WARFRAME_TRACKER_DB_PASS
        sync: false
      - key: WARFRAME_TRACKER_DB_NAME
        sync: false
      - key: WARFRAME_TRACKER_APPLY_MIGRATIONS
        value: "1"
      - key: ASPNETCORE_FORWARDEDHEADERS_ENABLED
        value: true
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
