param(
    [string]$TrackerUrl
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$configPath = Join-Path $projectRoot 'tracker.config.json'
if ([string]::IsNullOrWhiteSpace($TrackerUrl)) {
    $TrackerUrl = $env:WARFRAME_TRACKER_PUBLIC_URL
}
if ([string]::IsNullOrWhiteSpace($TrackerUrl) -and (Test-Path -LiteralPath $configPath)) {
    $TrackerUrl = (Get-Content -LiteralPath $configPath -Raw -Encoding utf8 | ConvertFrom-Json).trackerUrl
}
if ([string]::IsNullOrWhiteSpace($TrackerUrl)) {
    throw 'Define trackerUrl in tracker.config.json, pass -TrackerUrl, or set WARFRAME_TRACKER_PUBLIC_URL.'
}
$candidate = [Uri]$TrackerUrl
if ($candidate.AbsolutePath -eq '/') {
    $TrackerUrl = $TrackerUrl.TrimEnd('/') + '/native-sync'
}
$uri = [Uri]$TrackerUrl
if (-not $uri.IsAbsoluteUri) { throw 'TrackerUrl must be an absolute URL.' }
$isLoopback = $uri.Host -in @('localhost', '127.0.0.1')
if ($uri.Scheme -ne 'https' -and -not ($isLoopback -and $uri.Scheme -eq 'http')) {
    throw 'Use HTTPS. HTTP is accepted only for localhost development.'
}
$origin = $uri.GetLeftPart([UriPartial]::Authority)

[IO.File]::WriteAllText(
    $configPath,
    (@{ trackerUrl = $uri.AbsoluteUri } | ConvertTo-Json) + "`r`n",
    [Text.UTF8Encoding]::new($false))

$runtimePath = Join-Path $projectRoot 'public\runtime-config.js'
$serializedUrl = ConvertTo-Json $uri.AbsoluteUri -Compress
[IO.File]::WriteAllText(
    $runtimePath,
    "// Generated by Configurar-Tracker.ps1.`r`nwindow.WarframeTrackerNativeConfig = { trackerUrl: $serializedUrl };`r`n",
    [Text.UTF8Encoding]::new($false))

$manifestPath = Join-Path $projectRoot 'manifest.json'
$manifest = Get-Content -LiteralPath $manifestPath -Raw -Encoding utf8 | ConvertFrom-Json
$matches = @($manifest.data.externally_connectable.matches) + $origin
$manifest.data.externally_connectable.matches = @($matches | Sort-Object -Unique)
[IO.File]::WriteAllText(
    $manifestPath,
    ($manifest | ConvertTo-Json -Depth 30) + "`r`n",
    [Text.UTF8Encoding]::new($false))

$htmlPath = Join-Path $projectRoot 'public\main.html'
$html = Get-Content -LiteralPath $htmlPath -Raw -Encoding utf8
if (-not $html.Contains("frame-src $origin ") -and -not $html.Contains(" $origin;")) {
    $html = $html.Replace('frame-src ', "frame-src $origin ")
    [IO.File]::WriteAllText($htmlPath, $html, [Text.UTF8Encoding]::new($false))
}

Write-Host "Native Tracker URL configured: $($uri.AbsoluteUri)"
Write-Host "Allowed origin added to manifest and CSP: $origin"
Write-Host 'Next: npm run validate:official'
