<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Warframe Tracker GEP Test</AssemblyName>
    <RootNamespace>WarframeTracker.DevGepLauncher</RootNamespace>
    <ApplicationIcon Condition="Exists('..\..\desktop-electron\build\icon.ico')">..\..\desktop-electron\build\icon.ico</ApplicationIcon>
  </PropertyGroup>
</Project>
